# .github/workflows/test.yml
name: Test on push

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  pre-commit-check:
    name: Run pre-commit hooks (Ruff, GittyLeaks, Pytest)
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      tests-result: ${{ steps.run-pre-commit.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Install pre-commit
        run: uv run pre-commit install

      - name: Run all pre-commit hooks on all files
        id: run-pre-commit
        run: uv run pre-commit run --all-files

  create_issue_if_failed:
    name: Create Issue if Pre-commit Fails
    runs-on: ubuntu-latest
    needs: pre-commit-check
    if: needs.pre-commit-check.result == 'failure'
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: '❌ Pre-commit Checks Failed on ${{ github.ref_name }}',

  close_issue_if_fixed:
    name: Close Issue if Pre-commit Fixed
    runs-on: ubuntu-latest
    needs: pre-commit-check
    if: needs.pre-commit-check.result == 'success'
    steps:
      - name: Close matching issue
        uses: actions/github-script@v6
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.name,
              state: 'open',
              labels: 'bug,tests'
            });

            const issue = issues.data.find(issue =>
              issue.title.includes('❌ Pre-commit Checks Failed') &&
              !issue.pull_request
            );

            if (issue) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: issue.number,
                body: '✅ Pre-commit checks now pass. Closing this issue automatically.'
              });

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: issue.number,
                state: 'closed'
              });
            } else {
              console.log('No matching issue found.');
            }