# .github/workflows/test.yml
name: Test on push

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  pre-commit-check:
    name: Run pre-commit hooks (Ruff, GittyLeaks, Pytest)
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      tests-result: ${{ steps.run-pre-commit.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Install pre-commit
        run: uv run pre-commit install

      - name: Run all pre-commit hooks on all files
        id: run-pre-commit
        run: uv run pre-commit run --all-files

  create_issue_if_failed:
    name: Create Issue if Pre-commit Fails
    runs-on: ubuntu-latest
    needs: pre-commit-check
    if: needs.pre-commit-check.result == 'failure'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            
            // Check if issue already exists
            const existingIssues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'bug,tests'
            });

            const existingIssue = existingIssues.data.find(issue =>
              issue.title.includes('❌ Pre-commit Checks Failed') &&
              !issue.pull_request
            );

            if (!existingIssue) {
              await github.rest.issues.create({
                owner,
                repo,
                title: '❌ Pre-commit Checks Failed on ${{ github.ref_name }}',
                body: `Pre-commit checks failed on branch \`${{ github.ref_name }}\`.
                
**Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
**Commit:** ${{ github.sha }}

Please check the workflow logs and fix the issues.`,
                labels: ['bug', 'tests']
              });
              console.log('Created new issue for pre-commit failure');
            } else {
              console.log('Issue already exists for pre-commit failure');
            }

  close_issue_if_fixed:
    name: Close Issue if Pre-commit Fixed
    runs-on: ubuntu-latest
    needs: pre-commit-check
    if: needs.pre-commit-check.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Close matching issue
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'bug,tests'
            });

            const issue = issues.data.find(issue =>
              issue.title.includes('❌ Pre-commit Checks Failed') &&
              !issue.pull_request
            );

            if (issue) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issue.number,
                body: '✅ Pre-commit checks now pass. Closing this issue automatically.\n\n**Fixed in:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
              });

              await github.rest.issues.update({
                owner,
                repo,
                issue_number: issue.number,
                state: 'closed'
              });
              console.log(`Closed issue #${issue.number}`);
            } else {
              console.log('No matching issue found to close.');
            }